### ISSUE TITLE
Binning normalization in power plots

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui-Advanced-Tools#1]
Probably there is an issue with normalization of power plots numerical data. In an oversimplified simplified example below, a power load from the first harmonic in focus is estimated ([example.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5366299/example.zip)). Although a geometry of distribution seems OK and total power agrees with loop input, there is an issue with numerical values of bins:
1) If one supposes numerical values of bins to be in W/mm^2 and calculate total power load by summation of bins (considering bin area), the resulting value (0.065 W in the example) will be in strong disagreement with loop input (0.435 W).
2) The average power density given in the screenshot (7.915 W/mm^2) agrees with averaging of numerical bin values, but seems meaningless, since actually the example considers 0.435 W in ~0.2*0.2 mm area.

![Screenshot from 2020-10-12 23-16-25](https://user-images.githubusercontent.com/42113408/95769186-b217a100-0ce1-11eb-9783-c212fdd79c9d.png)
![Screenshot from 2020-10-12 23-20-40](https://user-images.githubusercontent.com/42113408/95769223-be9bf980-0ce1-11eb-9356-a87cc64ee5d2.png)

**Comment by lucarebuffi** [comment]
Dear Sergey, you sampled the energy with just 10 steps, there is no way you can have a reasonable result. The result is widely dependent on the sampling of both the input spectrum (XOPPY widget) and the sampling for the power (loop widget). Please read carefully the literature.

https://onlinelibrary.wiley.com/iucr/doi/10.1107/S160057752000778X

**Comment by lucarebuffi** [comment]
It is worth noting that you also put a 5 x 5 bins output plot, in this way you are going to loose a lot of details. Use a much finer sampling, so you can see details, and then you can decide in post-processing to reduce the number of bins and/or smooth the result.

**Comment by lucarebuffi** [comment]
Here my revised version

[therm_load.ows.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5366642/therm_load.ows.zip)

**Comment by lucarebuffi** [comment]
To check the goodness of the sampling, you can see the cumulative plot in the source, too. It contains the original SRW propagation result, so you can see more clearly the presence of artifacts by a poor sampling:

![Screen Shot 2020-10-12 at 12 35 02 PM](https://user-images.githubusercontent.com/6713598/95775103-5caea600-0c87-11eb-96b0-b8dfa45e3072.png)

**Comment by lucarebuffi** [comment]
Another thing: the 1x1 slit at 30 meters abruptly cut the radiation, this is going to create diffraction features in the generated raytracing of the source. To generate the spatial/angular distributions of the rays you should choose a bigger space, then cut the rays with a slit.

**Comment by SergeyRa** [comment]
Dear Luca,

Thanks a lot for your kind attention!
However, the discussed problem is not directly related to sampling. Below you can find the same data calculated with 1000 energy steps for 100*100 2D histogram ([therm_load.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5366813/therm_load.zip)). As you can see, the total power should be 0.4 W in agreement with "Power Density Loop Point" widget estimation and "Plotted" output on the screenshot. However, when I integrate numerical output from HDF5 file (taking into account bin/pixel area), I obtain different value (~0.3 W). In my experience, the difference depends on the configuration and sampling, but always exists and may be quite large. Could you please clarify how thermal load of individual rays is averaged to produce 2D histogram?

![power](https://user-images.githubusercontent.com/42113408/95776963-7daae180-0cef-11eb-9f4a-de1530b8f082.png)

**Comment by lucarebuffi** [comment]
Please, read the paper. Everything is clearly explained there. I am uploading a new version of the example, there are other errors. Anyway, the values reported in the screen are the integration of the (cumulated) incident plot and the plot in the range (you should always put a range in the plot). 

this is the portion of the code that calculates the values in the title:

        if ticket_to_add == None:
            self.cumulated_power_plot = ticket['histogram'].sum()
        else:
            self.cumulated_power_plot += ticket['histogram'].sum()

        ticket['histogram'] /= (bin_h_size * bin_v_size)  # power density

**Comment by lucarebuffi** [comment]
I am going to give you a much more revised version of your example (is running), then I check that the stored file container the correct and displayed values.

**Comment by SergeyRa** [comment]
Thanks a lot! I already checked that it is the limits of histogram that caused discrepancy in my results!
By the way, could you also comment in which cases the option "send power step" in the loop widget should be activated?

**Comment by lucarebuffi** [comment]
That option is done to speed up the calculation, but it is risky: the source widget does not recalculate the total power of every single step, but uses the one coming from the loop widget. 

This approach is potentially a source of nasty artifacts and should not be used, since there are small but sometimes significant differences between the calculation done to compute the spectrum and the one to propagate the wavefront.
It is more accurate to let SRW do the job and create a raytracing where the total power is calculated according to the energy step and the integral of the radiation used to create the spatial/angular distributions.

**Comment by SergeyRa** [comment]
Thanks for the explanation!

**Comment by lucarebuffi** [comment]
[Archive.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/5367434/Archive.zip)

Here is the improved example with explanations. As you can see, by correcting the wavefront propagation part (no diffraction effects), the result is quite different

![Uploading Screen Shot 2020-10-12 at 3.56.59 PM.png…]()

**Comment by lucarebuffi** [comment]
Here is the power density generated before the initial slits.

![Screen Shot 2020-10-12 at 3 57 25 PM](https://user-images.githubusercontent.com/6713598/95789924-0865ef00-0ca4-11eb-9a51-caaaf29535b9.png)

**Comment by lucarebuffi** [comment]
This calculation is very delicate and it is easy to make mistakes. Feel free to contact me privately until you learned all the tricks and master the calculation yourself.

**Comment by SergeyRa** [comment]
Dear Luca,

Thanks a lot for your enthusiastic assistance!

_P.S. I am aware of diffraction effects in source size estimation by back propagation. However, shouldn't we expect the same effect to take place in forward propagation, so that aperture which limits wavefront, imposes diffraction limit on both source size (corresponding to back propagation) and focus size (corresponding to mathematically equivalent forward propagation)? In such a case the enlarged "effective" source size caused by wavefront-limiting aperture allows to obtain reasonable focus size using just ray tracing, whereas in the case of "proper" source size estimation (i.e. by back propagation of large portion of wavefront) ray tracing will need an additional correction (i.e. by HYBRID) in order to account the fact that the "real" source size is actually too small to be observed through the given aperture._
