### ISSUE TITLE
Footprint Reader from an external reflectivity file

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/ShadowOui-Advanced-Tools#2]
Dear Luca,
I'm sorry for bothering you, I have a small issue. I have been using the new Thermal Load tools to get the heatload in multilayer mirrors. For me the algorithm works pretty smooth when the Reflectivity is generated by the **PreMLayer** widget. However, I still do not manage to make it work for the option of _User defined file_(for instance the file generated from XOPPY: Multilayer or IDM). 
Even though the ray tracing seems to work perfectly with these files, it is not the case for the footprint reader, and therefore the Power plot XY shows weird results.

Then, I wonder if, may be the footprint reader is not compatible with this option; or, I'm just doing something wrong (which is highly possible).

Best regards,
Juan

**Comment by lucarebuffi** [comment]
The user defined file is managed outside shadow3 by ShadowOui after the raytracing. For this reason you won't see any effects on the footprint, that is generated by shadow3. For those cases you must rely on the PreMLayer only. 
To extend the calculation on the footprint one must do quite a coding work...I'll think about it, but I can't promise anything anytime soon.

**Comment by jureyherrera** [comment]
Thank you for your reply Luca. Cheers, J
