### ISSUE TITLE
Detail in the Power Plot XY widget

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/ShadowOui-Advanced-Tools#4]
Dear Luca, 
I have been encounter a small issue with the Power Plot XY - Undulator widget. When the ShadowOui workflow is running, the widget sends every time an error: _Data not plottable:'NoneType' object has no attribute 'add_atribute'_
![image](https://user-images.githubusercontent.com/31166917/115356825-52341280-a1bc-11eb-96cd-c293d6c6e6fe.png)

It seems that the problem stops just by selecting **Yes** in the Autosave option, then the algorithm runs smoothly.

**Comment by lucarebuffi** [comment]
Thank you for tip, Juan!
I actually never used the software without saving the file automatically, so I never noticed the problem. I'll fix it asap, in the meantime, just turn on autosave.

**Comment by lucarebuffi** [comment]
fixed in 1.0.63
