### ISSUE TITLE
Loading file in Power Plot XY - Undulator

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/ShadowOui-Advanced-Tools#5]
Hello there,

I have an issue when trying to load an hdf5 in the widget, I'm having the following error:

_--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):_
_File "...\Python37\site-packages\orangecontrib\shadow_advanced_tools\widgets\thermal\ow_power_plot_xy.py", line 1068, in selectPlotFile
    ticket["histogram"], ticket["histogram_h"], ticket["histogram_v"], attributes = plot_file.get_last_plot(dataset_name="power_density")
  File "...\Python37\site-packages\orangecontrib\shadow\util\shadow_util.py", line 885, in get_last_plot
    return self.get_plot_xy(dataset_name=dataset_name)
  File "...\Python37\site-packages\orangecontrib\shadow\util\shadow_util.py", line 896, in get_plot_xy
    histogram = self["/xy_plots/" + plot_name + "/" + dataset_name].value
AttributeError: 'Dataset' object has no attribute 'value'
--------------------------------------------------------------------------------_

It's important to mention that the hdf5 has been created (Autosaved) by the same widget. FYI, an example file is here: [ml_pow_dens_premlayer.hdf5](https://github.com/jureyherrera/Misc_repo/blob/main/oasys_files/ml_pow_dens_premlayer.hdf5)

Thanks in advance for your attention.
Cheers, Juan

**Comment by lucarebuffi** [comment]
It looks like you have a non-standard version of OASYS. Apparently your hdf5 package is not the correct one (too recent).
Proper OASYS distributions don't show the issue. It must be said that very soon the code will be changed, because the attribute value is planned to be removed and replaced: dataset.value -> dataset[()]

**Comment by lucarebuffi** [comment]
downgrade h5py to 2.9.0, and you should be fine

**Comment by lucarebuffi** [comment]
Anyway, I quickly fixed it, upgrade both ShadowOui and the advanced tools.

**Comment by jureyherrera** [comment]
Now it is working very well, thanks a lot.
