### ISSUE TITLE
power density loop doesn't seem to work for BM

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/ShadowOui-Advanced-Tools#7]
Good Morning, and Happy New Year! 

I discovered this morning that the Power density Loop doesn't work for BM. I attach the .ows file here for your convenience. 
What I see is that the energy in the Shadow BM widget does not change at every loop step, while the MC seed does. 
I tried mimicking the 2020 paper, and used the XOPPY BM widget as input, set as below: 
![image](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/assets/41440861/4c8325e0-e9f1-470e-9b79-4353ddaa44d0)

But the Power Density Loop Point sees this: 
![image](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/assets/41440861/db81e688-e49d-4d25-92a8-848930f95b2d)

I thought the 2 things are correlated. 
I also tried to save the I tried to save the ph/s/0.1%bw file from the XOPPY widget, but the issue stay the same: the energy in the BM widget does not change. 

[BM Power Loop.ows.zip](https://github.com/oasys-kit/ShadowOui-Advanced-Tools/files/13885480/BM.Power.Loop.ows.zip)

**Comment by lucarebuffi** [comment]
As the title of the related paper says, the thermal load loop set of widgets for UNDULATOR SOURCES, only: 

https://scripts.iucr.org/cgi-bin/paper?S160057752000778X

It won't work for BM.

Moreover, you don't need a loop for the BM: you just attach a Power Density (BM) wherever you want on your beam line and input to it the Xoppy BM widget directly. The Shadow BM source and the XOPPY BM must be, of course, consistent with each other.

Please contact me directly next time.
